/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>

using namespace cv;
using namespace std;
/* Header for class com_hcilab_nkbminh_smiledetection_opencv_OpenCVNative */

#ifndef _Included_com_hcilab_nkbminh_smiledetection_opencv_OpenCVNative
#define _Included_com_hcilab_nkbminh_smiledetection_opencv_OpenCVNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hcilab_nkbminh_smiledetection_opencv_OpenCVNative
 * Method:    getTestMessage
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hcilab_nkbminh_smiledetection_1opencv_OpenCVNative_getTestMessage
  (JNIEnv *, jclass);

/*
 * Class:     com_hcilab_nkbminh_smiledetection_opencv_OpenCVNative
 * Method:    getTestMessageNew
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hcilab_nkbminh_smiledetection_1opencv_OpenCVNative_getTestMessageNew
        (JNIEnv *, jclass);

/*
 * Class:     com_hcilab_nkbminh_smiledetection_opencv_OpenCVNative
 * Method:    convertToGray
 * Signature: ()Ljava/lang/int;
 */
JNIEXPORT jint JNICALL Java_com_hcilab_nkbminh_smiledetection_1opencv_OpenCVNative_convertToGray
        (JNIEnv *, jclass, jlong, jlong);

int toGray(Mat img, Mat &gray);

/*
 * Class:     com_hcilab_nkbminh_smiledetection_opencv_OpenCVNative
 * Method:    faceDetection
 * Signature: ()Ljava/lang/void;
 */
JNIEXPORT jint JNICALL Java_com_hcilab_nkbminh_smiledetection_1opencv_OpenCVNative_faceDetection
        (JNIEnv *, jclass, jlong);

void detectFaces(Mat &frame);

#ifdef __cplusplus
}
#endif
#endif
